# Generated by Django 3.2.3 on 2021-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of_question',
            new_name='number_of_questions',
        ),
    ]
